default: &default
  adapter: postgresql

development:
  <<: *default
  database: angular_example_development

test:
  <<: *default
  database: angular_example_test

production:
  <<: *default
  database: angular_example_production
